### PR TITLE
Restrict extension to the primary monitor

### PR DESCRIPTION
**Pull request by vltr**
This PR basically adds the option to restrict the overall extension functionality to the primary screen (if enabled, default) or all screens (if disabled). This affects the window decorations, window buttons and application menu.

### CODE REVIEW

**Comment by jonian** [comment]
Thank you for your contribution. Maybe you can get `restrict-to-primary-screen` setting in the helper function to avoid repetition. In the helper file you can get the setting with:

```js
const Settings = Unite.imports.convenience.getSettings();

Settings.getSetting('restrict-to-primary-screen')
```

**Comment by vltr** [comment]
Thanks, @jonian ! I was in doubt if having a setting getter inside `helpers.js` would be a good idea - hence why I made this way, but since I agree with you it would be better to avoid repetition.

Should I leave the signals on their respective modules? (I guess they should because they may have to work based on its value).

**Comment by jonian** [comment]
@vltr Sorry for the late response. Yes, you should leave the signals on their respective modules. They are used to apply changes without restarting the shell.

**Comment by vltr** [comment]
@jonian don't worry :wink:

> They are used to apply changes without restarting the shell.

That was exactly my thought. I'll update this PR shortly after.

**Comment by vltr** [comment]
Done. I had made this change in my computer yesterday already and the extension is running flawlessly (so far) :muscle:

**Comment by jonian** [comment]
Fixes issue #61

**Comment by vltr** [comment]
> Great! Thank you for contributing.

It was my pleasure :wink: Thanks a lot!

**Comment by vltr** [comment]
Oh, @jonian , I did not change any `metadata` or the `README` file because I guess the maintainers would like to do that when the next release comes to light :smiley:

**Pull request merged**
