### PR TITLE
panel: remove flags from allocate call

### PR DESCRIPTION
**Pull request by BjoernDaase**
Similar to https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/9b99b67feabef01cb30e89962e50c094952d8852 to silence warnings in 3.38.

### CODE REVIEW

**Comment by jonian** [comment]
Thank you for the contribution @BjoernDaase! Any idea if this needs version checking for GS < 3.38?

**Comment by BjoernDaase** [comment]
Hmm, I am not sure tbh, might be.
Unfortunately I currently do not have a 3.36 version, so maybe you could give it a try and see what happens?

**Comment by jonian** [comment]
I tested with 3.36 and it is not working, so version checking is required. If you need help on how to do it, please let me know.

**Comment by BjoernDaase** [comment]
Done.

I went for duplicating the whole `_allocate` function because I think its quite cumbersome to check for the version before every `allocate` call. But if you prefer, we can also do it that way.

**Comment by jonian** [comment]
Maybe you can do only checks in allocate functions by adding a class helper method:

```js
if (VERSION < 37) {
  Main.panel.vfunc_allocate.call(Main.panel, box, flags)
} else {
  Main.panel.vfunc_allocate.call(Main.panel, box)
}
```
```js
_boxAllocate(box, childBox, flags) {
  if (VERSION < 37) {
    box.allocate(childBox, flags)
  } else {
    box.allocate(childBox)
  }
}

this._boxAllocate(leftBox, childBox, flags)
this._boxAllocate(centerBox, childBox, flags)
this._boxAllocate(rightBox, childBox, flags)
```

**Comment by BjoernDaase** [comment]
Sounds good, done.

**Comment by jonian** [comment]
Thank you for your contribution!

**Pull request merged**
