### PR TITLE
[Enhancement] Adds the Flat-Remix theme buttons

### PR DESCRIPTION
**Pull request by rohanmohapatra**
Hi this PR adds the flat-remix theme [icons](https://github.com/daniruiz/flat-remix-gtk/tree/master/Flat-Remix-GTK-Blue-Dark/gtk-3.0/assets) which is a popular theme
[Flat Remix](https://github.com/daniruiz/flat-remix)
I have directly pulled the pngs from that repository

### CODE REVIEW

**Comment by jonian** [comment]
Hi @rohanmohapatra, thanks for the PR!

The preferred format for theme assets is `svg`. The svg assets for Flat Remix are available [here](https://github.com/daniruiz/flat-remix-gtk/blob/master/src/assets-renderer/gtk3/assets.svg). 

Also you should clean-up the svg asstets with and optimizer like [SVG Cleaner](https://github.com/RazrFalcon/SVGCleaner) or [svgo](https://github.com/svg/svgo).

With svgcleaner you can use the command:

```
svgcleaner --indent=2 in.svg out.svg
```
If you can't do this, it's ok, I will accept the PR and add those assets after.

**Comment by rohanmohapatra** [comment]
@jonian will update the PR, thanks for the suggestion

**Comment by rohanmohapatra** [comment]
@jonian I have use svg assets and applied the cleaner.
The theme is goot to merge

**Comment by jonian** [comment]
Thanks @rohanmohapatra!

**Pull request merged**
