### PR TITLE
Revert "Also check the disconnect handler to really fix the error on suspend"

### PR DESCRIPTION
**Pull request by jonian**
Reverts hardpixel/unite-shell#256

### CODE REVIEW

**Comment by jonian** [comment]
@njsf reverting this as it causes stops any signal from disconnecting, you can try it by adding a log inside the if clause.

**Comment by njsf** [comment]
> @njsf reverting this as it stops any signal from disconnecting, you can try it by adding a log inside the if clause.

Ok, will looking into it.

**Comment by jonian** [comment]
@njsf the issue is caused in this [line](https://github.com/hardpixel/unite-shell/blob/e6029c7592b902ae7b69032f8eac7ffe4e6e2a17/unite%40hardpixel.eu/layout.js#L145). My guess is that the problem begins [here](https://github.com/hardpixel/unite-shell/blob/e6029c7592b902ae7b69032f8eac7ffe4e6e2a17/unite%40hardpixel.eu/layout.js#L121), it uses `Main.panel.get_children()` instead of explicitly connecting to left, center and right panel boxes. If another extension adds children to Main.panel it is possible to have signal connections to objects that no longer exist. Can you try with the fix below:

```js
activate() {
  this.signals = new Handlers.Signals()

  const boxes = [
    Main.panel._leftBox,
    Main.panel._centerBox,
    Main.panel._rightBox
  ]

  for (const box of boxes) {
    this.signals.connect(
      box, 'actor_added', this._onActorAdded.bind(this)
    )
  }

  this._onActorAdded()
}
```

I have already pushed this fix on master branch

**Comment by njsf** [comment]
Indeed the issue is gone.  I suspect you can revert #255 also.
Thanks for looking at this

**Comment by jonian** [comment]
Thanks confirming the issue is resolved. I will keep #255 as it is just a safety check and it does not cause issues.

**Pull request merged**
